name: salmogp

dependencies:
  - pip
  - python=3.8.10
  - pip:
    - cloudpickle==1.6.0
    - gpflow==2.1.4
    - matplotlib==3.4.2
    - numpy==1.19.2
    - pandas==1.1.5
    - scipy==1.7.0
    - tensorflow==2.4.0
    - tensorflow-probability==0.12.2
    
